services:
  - type: web
    name: tic-tac-toe-ai
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput"
    startCommand: "gunicorn tictactoe_project.wsgi"
